### ISSUE TITLE
Module not found: Can't resolve '~~/utils/generateInitialValues'

### ISSUE THREAD

**Issue by neerajnerlekar** [d4rm5/eip712-builder#1]
On initial install of the extension, the import is not recognized.

![image](https://github.com/user-attachments/assets/c7b2f894-3ffd-4ade-a63e-2d9b6576d7a2)

Changing the import from
```typescript
import {generateInitialValues} from '~~/utils/generateInitialValues';
```

To

```typescript
import { generateInitialValues } from "../_utils/generateInitialValues";
```

fixed it.

![image](https://github.com/user-attachments/assets/4302b4f6-1acd-4fdd-87d9-d9cc650f7784)

**Comment by d4rm5** [comment]
Fixed in last commit, thanks!
